### PR TITLE
fixes deployment with compose v2.0

### PR DESCRIPTION
**Pull request by gonzalochief**
Composer v2.0 broke all dependencies. Now it is a sub command.

### CODE REVIEW

**Comment by gonzalochief** [comment]
I have already tested it on my deployment. I installed Docker Compose v2.0 and with the proposed changes, it works. Must be a new version

**Comment by wshihadeh** [comment]
This will brake it for older versions, can you please update this in a way that supports both versions

**Comment by admin-andikem** [comment]
Let me see if i can do that by adding a new parameter (like compose version - 1 0r 2) and then a conditional in the bash script.

**Comment by gonzalochief** [comment]
I've launched a new pull request adding v1 and v2 support

**Pull request closed without merging**
